# Lychee configuration
# Ignore mailto links and anchors
exclude = ["mailto:*", "#*", "http://localhost.*", "https://localhost.*"]
# Output format
format = "json"
# Output file
output = "reports/links.json"