name: Post-Deploy Health Check
on:
  workflow_run:
    workflows: ["Deploy WEB to Azure", "Deploy API to Azure"]
    types: [completed]
  workflow_dispatch:
    inputs:
      web_url:
        description: 'Web app URL to check'
        required: false
        default: 'https://econeura-web-dev.azurewebsites.net'
      api_url:
        description: 'API URL to check'
        required: false
        default: 'https://econeura-api-dev.azurewebsites.net'
  schedule:
    - cron: "0 */6 * * *"  # Every 6 hours
permissions:
  contents: read
jobs:
  health:
    runs-on: ubuntu-latest
    steps:
      - name: Check WEB
        run: |
          URL="${{ github.event.inputs.web_url || 'https://econeura-web-dev.azurewebsites.net' }}"
          echo "Checking web health at: $URL"
          for i in {1..3}; do
            if curl -fsS --max-time 30 "$URL" >/dev/null; then
              echo "✅ WEB OK (attempt $i)"
              break
            else
              echo "Attempt $i failed, retrying in 5s..."
              sleep 5
            fi
          done
          if [ $i -eq 3 ]; then
            echo "❌ WEB DOWN after 3 attempts: $URL"
            exit 10
          fi

      - name: Check API /api/health
        run: |
          API="${{ github.event.inputs.api_url || 'https://econeura-api-dev.azurewebsites.net' }}"
          echo "Checking API health at: $API/api/health"
          for i in {1..3}; do
            if curl -fsS -H "X-Correlation-Id: health-check-$(date +%s)" --max-time 30 "$API/api/health" >/dev/null; then
              echo "✅ API health OK (attempt $i)"
              break
            else
              echo "Attempt $i failed, retrying in 5s..."
              sleep 5
            fi
          done
          if [ $i -eq 3 ]; then
            echo "❌ API health FAIL after 3 attempts: $API/api/health"
            exit 11
          fi

      - name: Test agent routing (sample agents)
        run: |
          API="${{ github.event.inputs.api_url || 'https://econeura-api-dev.azurewebsites.net' }}"
          echo "Testing agent routing with sample requests..."
          # Test a few key agents
          for agent in "ceo_orquestador" "ia_a1" "cfo_doctor_coach"; do
            echo "Testing agent: $agent"
            response=$(curl -s -w "%{http_code}" -o /dev/null --max-time 30 \
              -H "Authorization: Bearer health-check-token" \
              -H "X-Correlation-Id: health-check-$(date +%s)" \
              -H "X-Route: azure" \
              -d '{"input":"health check"}' \
              "$API/api/invoke/$agent" 2>/dev/null || echo "000")
            if [ "$response" = "200" ] || [ "$response" = "401" ] || [ "$response" = "403" ]; then
              echo "✅ Agent $agent routing OK (HTTP $response)"
            else
              echo "⚠️ Agent $agent returned HTTP $response (might be expected for auth)"
            fi
          done

      - name: Validate web app content
        run: |
          URL="${{ github.event.inputs.web_url || 'https://econeura-web-dev.azurewebsites.net' }}"
          echo "Validating web app content..."
          content=$(curl -s --max-time 30 "$URL" || echo "")
          if echo "$content" | grep -q "react"; then
            echo "✅ React app detected in response"
          else
            echo "⚠️ No React content detected"
          fi
          if echo "$content" | grep -q "ECONEURA\|cockpit\|neura"; then
            echo "✅ App-specific content detected"
          else
            echo "⚠️ No app-specific content detected"
          fi
